# Generated by Django 5.1.1 on 2024-09-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='drive',
            field=models.TimeField(verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.TimeField(verbose_name='Название'),
        ),
    ]
