# Generated by Django 5.1.1 on 2024-09-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_options_alter_car_drive_alter_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='drive',
            new_name='drive_name',
        ),
    ]
