# Generated by Django 5.1.1 on 2024-09-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_drive_car_drive_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.drive'),
        ),
    ]
