# Generated by Django 5.1.1 on 2024-09-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_drive_car_drive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drive',
            options={'verbose_name': 'Привод', 'verbose_name_plural': 'Приводы'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive_name',
        ),
    ]
