# Generated by Django 5.1.1 on 2024-09-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_enginetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.enginetype'),
        ),
    ]
