# Generated by Django 5.1.1 on 2024-09-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
