# Generated by Django 5.1.1 on 2024-09-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_bodytype_alter_enginetype_etype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='etype',
        ),
        migrations.AddField(
            model_name='car',
            name='btype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.bodytype'),
        ),
    ]
