# Generated by Django 5.1.1 on 2024-09-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_rename_type_car_etype_car_btype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trtype', models.TextField(verbose_name='Тип КПП')),
            ],
            options={
                'verbose_name': 'Тип кпп',
                'verbose_name_plural': 'Типы кпп',
            },
        ),
    ]
