# Generated by Django 5.1.1 on 2024-11-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_drive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
