# Generated by Django 5.1.1 on 2024-11-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_bodytype_description_enginetype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='cars', verbose_name='Изображение'),
        ),
    ]
