# Generated by Django 5.1.1 on 2024-11-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_car_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytype',
            name='picture',
            field=models.ImageField(null=True, upload_to='bodytypes', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='drive',
            name='picture',
            field=models.ImageField(null=True, upload_to='drives', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='enginetype',
            name='picture',
            field=models.ImageField(null=True, upload_to='enginetypes', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='transmissiontype',
            name='picture',
            field=models.ImageField(null=True, upload_to='transmissiontypes', verbose_name='Изображение'),
        ),
    ]
