# Generated by Django 5.1.1 on 2024-11-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_rename_user_car_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='user',
        ),
    ]
